### ISSUE TITLE
errors in dokuwiki version

### ISSUE THREAD

**Issue by ggieling** [mprins/dokuwiki-plugin-backlinks#24]
## environment

  - php version: 7.0.30-0026
  - dokuwiki version: Release 2018-04-22a "Greebo"
  - plugin version / date: 2018-06-20
  - list of any other plugins (apart from bundled plugins): 
edittable
include
move
page redirect
simplenavi
tablecalc
  
## expected behaviour
Expect it to work

## error message:
Warning: Declaration of syntax_plugin_backlinks::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /volume1/web/dokuwiki/lib/plugins/backlinks/syntax.php on line 0 Warning: Declaration of syntax_plugin_backlinks::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /volume1/web/dokuwiki/lib/plugins/backlinks/syntax.php on line 0

## steps to reproduce actual behaviour
Just try to install it
Automatic installation using "search and install" fails
Manual install runs but results in wiki producing above error messages
Instruction to include backlinks results in the following link in the page
'[SERVERNAME]/dokuwiki/lib/exe/fetch.php?tok=4f59f6&media=https%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3D.%26amp%3BbtnI%3Dlucky'
instead of expected list of pages in wiki referring to page.

### error log

```
ERRORS
```

### debug log

```
DEBUG
```

**Comment by mprins** [comment]
download links should point back to this github repository; if they don't the url you are getting from dokuwiki.org is wrong or you are not installing what you think you are installing. 
Since dokuwiki.org is a wiki vandalism happens, but the good thing is you can correct it there: https://www.dokuwiki.org/plugin:backlinks2

ps. I just check and the download link is correct; there is nothing left for me to do

**Comment by hershelsr** [comment]
I also found that the automatic install fails and so I manually installed using:

https://github.com/mprins/dokuwiki-plugin-backlinks/archive/master.zip

and this tag: {{backlinks>.}} produces this text: search?q=.&amp;btnI=lucky which is a link to:

http://mywiki.net/lib/exe/fetch.php?tok=8ce05b&media=https%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3D.%26amp%3BbtnI%3Dlucky

Seems this is the same thing the original poster reported. There is indeed a problem here.

**Comment by mprins** [comment]
none of the words "lucky", "google" or "search" occur in this codebase, you must be using a plugin that is messing with things. I suggest you turn of asl plugins and start with backlinks2 and the see when things break.
Since this is not a support forum I suggest you take any further questions to th emailing list
